### ISSUE TITLE
A1 Task3

### ISSUE THREAD

**Issue by rxxq** [rxxq/CSCC67-assignment-notes#4]
@jaydoncct 
@crazyo 
#### Tasks:
- [x] getpid (@crazyo)
- [x] waitpid (@crazyo)
- Kill:
  - [x] pid_ischild (@rxxq)
  - [x] sigflag functions (@rxxq) (Done but needs testing)
  - [x] function for the target process to check flags and take appropriate action (@crazyo)
  - [x] The syscall function for sending signals (@rxxq)
- [x] Make sure everything works before we submit (@jaydoncct)

**Comment by rxxq** [comment]
The pid_ischild and sigflag functions can be found in `rex/syscalls_kill_a1t3` branch. Also, in that branch there is a todo comment in trap.c indicating where I think the flags should be checked.

**Comment by rxxq** [comment]
I've implemented the sigflag functions, but I haven't tested them yet. Also, I need to define constants for all 32 signals somewhere.

**Comment by rxxq** [comment]
**EDIT** _Ignore this comment, see comment below_
I've defined constants for all 32 signals. To use them (in kernel code) you need to import

``` C
#include <kernel/signals.h>
```

**Comment by rxxq** [comment]
I just realized that constants for the 32 signals are already defined in `src/kernel/include/kernel/signal.h` (notice its signal not signal_s_). So instead, I added a `SIGSET` macro in `signal.h` to convert between the signal numbers (from 1 to 32) to bitmasks of the `sigset_t` type.
